/** p4 (Perforce) 命令封装。
 *
 * 所有操作限定在指定的 client workspace 内，通过子进程 env 注入
 * P4PORT/P4CLIENT/P4USER/P4PASSWD。安全约定：本模块只提供
 * sync / opened / diff / reconcile / revert / change 相关操作；
 * submit 仅由 auto 模式显式调用。
 *
 * 全部方法异步（Promise），避免 p4 sync 等长命令阻塞 Node 事件循环。
 */

import { execFileSync, spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

// config.p4 键 -> 环境变量名
const _P4_ENV_MAP: Record<string, string> = {
  port: "P4PORT",
  client: "P4CLIENT",
  user: "P4USER",
  password: "P4PASSWD",
  config: "P4CONFIG",
  ignore: "P4IGNORE",
};

/** 把 config.p4 段转成 P4 环境变量（port/client/user/password/config/ignore）。
 *  空值跳过。编排器（P4Client）和 Agent（pi）共用此 helper，保证两边
 *  用的 client/认证完全一致 —— 否则 Agent 的 p4 edit 落在别的 client 里，
 *  reconcile 后 opened 为空，导致「修复失败：未打开任何文件」。 */
export function p4EnvFromConfig(configP4: Record<string, string> = {}): Record<string, string> {
  const env: Record<string, string> = {};
  for (const [key, envName] of Object.entries(_P4_ENV_MAP)) {
    const val = configP4[key];
    if (val) env[envName] = String(val);
  }
  return env;
}

// p4 opened 行格式（注意 `change` 是 changelist 占位词，两种形态都有它）:
//   `//depot/path#rev - action default change (type)`
//   `//depot/path#rev - action change 1234 (type)`
// 之前正则写成 `(\S+)\s+#\S+`（路径与 #rev 间要求空白）且漏了 `default` 后的 `change`
// → 真实输出永远匹配失败 → opened() 恒返回空 → 所有成功修复都被误判「无 opened 文件」。
const _OPENED_RE = /^(\S+)#\S+\s+-\s+(\S+)\s+(?:default\s+change|change\s+(\d+))\s*\(([^)]*)\)/;
const _RECONCILE_RE = /^(.*?)#(?:\d+|none)\s+-\s+/;
const _CHANGE_CREATED_RE = /Change\s+(\d+)\s+created/i;
const _P4_SYNC_TIMEOUT_MS = 10 * 60 * 1000;
const _P4_TARGETED_SCAN_TIMEOUT_MS = 2 * 60 * 1000;
const _P4_PARALLEL_SYNC = "--parallel=threads=4,min=10";
export const GENERATED_P4IGNORE = ".tapd-bugfix-agent.p4ignore";

/** 只重试可能自行恢复的网络/文件占用错误；范围扫描超时和普通命令错误立即失败。 */
function isRetryableSyncError(error: P4Error): boolean {
  const message = error.message.toLowerCase();
  if (/超时\(\d+s\)|timed?\s*out/.test(message)) return false;
  return /tcp|socket|network|connect to server failed|connection (?:reset|closed|refused)|rename|file.*(?:in use|used by another process)|文件.*(?:占用|使用)/.test(message);
}

/** 由仓库 ignore_paths 生成 P4 原生规则，避免 P4 扫描大量未跟踪构建产物。 */
export function ensureP4IgnoreFile(workspacePath: string, ignorePaths: string[]): string | undefined {
  const rules = ignorePaths.map((value) => value.trim().replace(/\\/g, "/")).filter(Boolean);
  if (!rules.length) return undefined;
  const filePath = path.join(workspacePath, GENERATED_P4IGNORE);
  const content = [
    "# Generated by TapdBugFixAgent from repos[].ignore_paths; do not edit.",
    GENERATED_P4IGNORE,
    ...rules,
    "",
  ].join("\n");
  let current = "";
  try { current = fs.readFileSync(filePath, "utf-8").replace(/\r\n/g, "\n"); } catch { /* 首次创建 */ }
  if (current !== content) fs.writeFileSync(filePath, content, "utf-8");
  return GENERATED_P4IGNORE;
}

const normalizeP4Path = (value: string): string => value
  .trim()
  .replace(/\\/g, "/")
  .replace(/^\.\//, "")
  .replace(/^\/+/, "")
  .toLowerCase();

const globRegex = (value: string): string => {
  let out = "";
  for (let i = 0; i < value.length; i += 1) {
    const char = value[i];
    if (char === "*" && value[i + 1] === "*") {
      out += ".*";
      i += 1;
    } else if (char === "*") {
      out += "[^/]*";
    } else if (char === "?") {
      out += "[^/]";
    } else {
      out += char.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }
  }
  return out;
};

/** P4 输出通常是 depot 路径，配置是工作区相对路径，因此允许在任意目录边界匹配。 */
export function p4PathIgnored(filePath: string, ignorePaths: string[]): boolean {
  const candidate = normalizeP4Path(filePath);
  return ignorePaths.some((raw) => {
    let rule = normalizeP4Path(raw);
    if (!rule) return false;
    if (rule.startsWith("**/")) rule = rule.slice(3);
    if (rule.endsWith("/")) rule += "**";
    return new RegExp(`(?:^|/)${globRegex(rule)}$`, "i").test(candidate);
  });
}

export interface OpenedFile {
  depot: string;
  action: string;
  changelist: string;
  type: string;
}

export class P4Error extends Error {}
/** P4 服务、网络或休眠恢复后的连接不可用；属于工作区基础设施阻塞，不是 Bug 修复失败。 */
export class P4ConnectionError extends P4Error {}
export class P4SyncTimeoutError extends P4Error {}
export class P4CancelledError extends P4Error {}

export function isP4ConnectionFailure(value: unknown): boolean {
  const message = String(value ?? "").toLowerCase();
  return /connect to server failed|tcp connect|connection (?:reset|closed|refused)|network (?:is )?unreachable|no route to host|unknown host|name or service not known|wsaeconnrefused|wsaeacces|wsahost_not_found|套接字|无法连接|连接.*(?:拒绝|重置|关闭)/i.test(message);
}

export interface P4CancellationSignal {
  readonly cancelled: boolean;
}

export function setSpecField(spec: string, field: string, value: string): string {
  const lines = spec.split(/\r?\n/);
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.startsWith(field + ":")) {
      out.push(field + ":");
      const valueLines = value.split(/\r?\n/);
      for (const vl of valueLines) out.push(vl ? "\t" + vl : "\t");
      i += 1;
      while (i < lines.length && (lines[i].startsWith("\t") || lines[i].startsWith(" "))) {
        i += 1;
      }
      continue;
    }
    out.push(line);
    i += 1;
  }
  return out.join("\n") + "\n";
}

interface P4RunOpts {
  cwd: string;
  env: NodeJS.ProcessEnv;
  input?: string;
  timeout?: number;
  cancelSignal?: P4CancellationSignal;
  onHeartbeat?: (elapsedSeconds: number) => void;
}

function killProcessTree(child: ChildProcess): void {
  if (child.pid === undefined || child.exitCode !== null) return;
  if (process.platform === "win32") {
    try {
      execFileSync("taskkill", ["/F", "/T", "/PID", String(child.pid)], {
        stdio: "ignore",
        timeout: 15000,
      });
    } catch {
      // 进程可能已退出
    }
  }
  try { child.kill(); } catch { /* ignore */ }
}

function runP4(args: string[], opts: P4RunOpts): Promise<{ stdout: string; stderr: string; code: number | null }> {
  return new Promise((resolve, reject) => {
    const child = spawn("p4", args, {
      cwd: opts.cwd,
      env: opts.env,
      windowsHide: true,
    });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const cleanup = (): void => {
      clearTimeout(timer);
      clearInterval(cancelWatchdog);
      clearInterval(heartbeat);
    };
    const fail = (error: Error): void => {
      if (settled) return;
      settled = true;
      cleanup();
      reject(error);
    };
    child.stdout?.on("data", (d: Buffer) => (stdout += d.toString()));
    child.stderr?.on("data", (d: Buffer) => (stderr += d.toString()));
    const timer = setTimeout(() => {
      killProcessTree(child);
      const ErrorType = args[0] === "sync" ? P4SyncTimeoutError : P4Error;
      fail(new ErrorType(`p4 ${args.join(" ")} 超时(${Math.round((opts.timeout ?? 120000) / 1000)}s)`));
    }, opts.timeout ?? 120000);
    const started = Date.now();
    const cancelWatchdog = setInterval(() => {
      if (!opts.cancelSignal?.cancelled) return;
      killProcessTree(child);
      fail(new P4CancelledError(`p4 ${args.join(" ")} 被人工取消`));
    }, 200);
    const heartbeat = setInterval(() => {
      opts.onHeartbeat?.(Math.round((Date.now() - started) / 1000));
    }, 30000);
    child.on("error", (err) => {
      fail(new P4Error(`无法执行 p4: ${err.message}`));
    });
    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      cleanup();
      resolve({ stdout, stderr, code });
    });
    if (opts.input !== undefined) {
      child.stdin?.write(opts.input);
    }
    child.stdin?.end();
  });
}

export class P4Client {
  path: string;
  env: NodeJS.ProcessEnv;
  readonly ignorePaths: string[];

  constructor(
    workspacePath: string,
    configP4: Record<string, string> = {},
    private readonly onLog?: (level: "debug" | "info" | "warn" | "error", message: string) => void,
    private readonly cancelSignal?: P4CancellationSignal,
    ignorePaths: string[] = [],
  ) {
    this.path = workspacePath;
    this.env = { ...process.env, ...p4EnvFromConfig(configP4) };
    this.ignorePaths = ignorePaths.map((value) => value.trim()).filter(Boolean);
  }

  private filterReconcileOutput(output: string): string {
    let ignoredEntry = false;
    return output.split(/\r?\n/).filter((line) => {
      const match = _RECONCILE_RE.exec(line);
      if (match) {
        ignoredEntry = p4PathIgnored(match[1], this.ignorePaths);
        return !ignoredEntry;
      }
      // `... depot/path - also opened by user@client` 属于上一条 reconcile 结果的续行。
      if (ignoredEntry && line.startsWith("... ")) return false;
      if (line.trim()) ignoredEntry = false;
      return true;
    }).join("\n").trim();
  }

  private reconcileFiles(output: string): string[] {
    return [...new Set(output.split(/\r?\n/).flatMap((line) => {
      const match = _RECONCILE_RE.exec(line);
      return match ? [match[1]] : [];
    }))];
  }

  async run(args: string[], inputText?: string, timeout = 120000): Promise<string> {
    const { stdout, stderr, code } = await runP4(args, {
      cwd: this.path,
      env: this.env,
      input: inputText,
      timeout,
      cancelSignal: this.cancelSignal,
      onHeartbeat: (elapsedSeconds) => this.onLog?.(
        "debug",
        `P4: p4 ${args.join(" ")} 仍在运行（已 ${elapsedSeconds}s）`,
      ),
    });
    if (code !== 0) {
      const err = stderr.trim() || stdout.trim() || "p4 failed";
      const message = `p4 ${args.join(" ")} 失败: ${err}`;
      throw isP4ConnectionFailure(message) ? new P4ConnectionError(message) : new P4Error(message);
    }
    return stdout;
  }

  sleep(ms: number): Promise<void> {
    return new Promise((r) => setTimeout(r, ms));
  }

  /**
   * 只读命令遇到休眠、VPN 或 P4 服务短暂重连时可安全重试。
   * 写命令不在这里自动重放，避免服务端已执行但客户端丢响应时产生重复副作用。
   */
  private async runReadWithReconnect(
    args: string[],
    timeout = 120000,
    attempts = 3,
    retryDelay = 3000,
  ): Promise<string> {
    let lastError: P4ConnectionError | undefined;
    for (let attempt = 0; attempt < Math.max(1, attempts); attempt += 1) {
      try {
        return await this.run(args, undefined, timeout);
      } catch (error) {
        if (error instanceof P4CancelledError) throw error;
        if (!(error instanceof P4ConnectionError)) throw error;
        lastError = error;
        const willRetry = attempt + 1 < Math.max(1, attempts);
        this.onLog?.(
          willRetry ? "warn" : "error",
          `P4: 连接失败（第 ${attempt + 1}/${Math.max(1, attempts)} 次）${willRetry ? `，${Math.round(retryDelay / 1000)}s 后重试` : ""}: ${error.message}`,
        );
        if (willRetry) await this.sleep(retryDelay);
      }
    }
    throw lastError ?? new P4ConnectionError(`p4 ${args.join(" ")} 连接失败`);
  }

  // ---------- 只读 ----------
  async sync(
    files: string[] = ["./..."],
    timeout = _P4_SYNC_TIMEOUT_MS,
    retries = 3,
    retryDelay = 5000,
  ): Promise<string> {
    const targets = files.map((file) => file.trim()).filter(Boolean);
    if (!targets.length) return "";
    const targetLabel = targets.length === 1 ? targets[0] : `${targets.length} 个目标文件`;
    let lastErr: P4Error | undefined;
    for (let attempt = 0; attempt < retries; attempt++) {
      const started = Date.now();
      this.onLog?.("info", `P4: 开始同步 ${targetLabel}（第 ${attempt + 1}/${retries} 次，超时 ${Math.round(timeout / 1000)}s）`);
      try {
        const output = await this.run(["sync", _P4_PARALLEL_SYNC, ...targets], undefined, timeout);
        this.onLog?.("info", `P4: ${targetLabel} 同步成功（第 ${attempt + 1}/${retries} 次，耗时 ${Math.round((Date.now() - started) / 1000)}s）`);
        return output;
      } catch (exc) {
        if (exc instanceof P4CancelledError) throw exc;
        lastErr = exc as P4Error;
        const willRetry = attempt < retries - 1 && isRetryableSyncError(lastErr);
        this.onLog?.(
          willRetry ? "warn" : "error",
          `P4: ${targetLabel} 同步失败（第 ${attempt + 1}/${retries} 次，耗时 ${Math.round((Date.now() - started) / 1000)}s${willRetry ? "，将重试" : "，不重试"}）: ${lastErr.message}`,
        );
        if (!willRetry) throw lastErr;
        await this.sleep(retryDelay);
      }
    }
    throw lastErr ?? new P4Error(`p4 sync ${targets.join(" ")} 失败`);
  }

  /** 返回打开的文件列表。changelist 传 "default" 只取 default changelist。
   *  重要：创建 pending changelist 的 Files 列表只允许 default 里的文件——p4 change
   *  规范明确 "Files: What opened files from the default changelist are to be
   *  added"。之前不带 -c 把其它 bug 已生成的编号 changelist 里的文件也收进来，
   *  p4 change -i 必报 "Can't include file(s) not already opened"，且成功越多失败越恒定。 */
  async opened(changelist?: string, strict = false): Promise<OpenedFile[]> {
    let out: string;
    try {
      out = changelist
        ? await this.runReadWithReconnect(["opened", "-c", changelist])
        : await this.runReadWithReconnect(["opened"]);
    } catch (error) {
      if (error instanceof P4CancelledError) throw error;
      if (/file\(s\) not opened/i.test(String(error))) return [];
      this.onLog?.(strict ? "error" : "warn", `P4: 查询 opened 失败${strict ? "" : "，按空结果继续"}: ${String(error)}`);
      if (strict) throw error;
      return [];
    }
    const result: OpenedFile[] = [];
    for (const line of out.split(/\r?\n/)) {
      const m = _OPENED_RE.exec(line);
      if (m && !p4PathIgnored(m[1], this.ignorePaths)) {
        result.push({
          depot: m[1],
          action: m[2],
          changelist: m[3] || "default",
          type: m[4],
        });
      }
    }
    return result;
  }

  /** 指定文件（不给则全部打开文件）的 unified diff。 */
  async diffUnified(files?: string[]): Promise<string> {
    try {
      const args = files && files.length ? ["diff", "-du", ...files] : ["diff", "-du"];
      // diff 仅用于结果展示，不能因为休眠后的 P4 断线拖住一个已经完成的修复。
      // 连接健康度已在任务开始时由 opened(..., true) 严格检查。
      return await this.run(args);
    } catch (error) {
      // diff 只用于验证展示，普通错误可降级；人工取消必须向上抛出。
      if (error instanceof P4CancelledError) throw error;
      if (error instanceof P4ConnectionError) {
        this.onLog?.("warn", `P4: diff 查询连接失败，按无可展示 diff 继续: ${error.message}`);
      }
      return "";
    }
  }

  /** 检测"改了文件但没 p4 edit/p4 add"的磁盘差异（-n 预览）。 */
  async reconcilePreview(files: string[] = ["./..."]): Promise<string> {
    try {
      const targets = [...new Set(files.map((file) => file.trim()).filter(Boolean))];
      if (!targets.length) return "";
      const output = await this.runReadWithReconnect(
        ["reconcile", "-n", ...targets],
        _P4_TARGETED_SCAN_TIMEOUT_MS,
      );
      return this.filterReconcileOutput(output);
    } catch (error) {
      if (error instanceof P4CancelledError || error instanceof P4ConnectionError) throw error;
      this.onLog?.("warn", `P4: reconcile -n 失败，按无本地改动继续: ${String(error)}`);
      return "";
    }
  }

  // ---------- 写操作（编排器专用）----------
  async reconcile(preview?: string): Promise<string> {
    const filtered = preview === undefined ? await this.reconcilePreview() : this.filterReconcileOutput(preview);
    if (!filtered) return "";
    const files = this.reconcileFiles(filtered);
    if (!files.length) throw new P4Error("无法解析 reconcile 预览中的文件路径，已拒绝执行全工作区 reconcile");
    return this.run(["reconcile", ...files]);
  }

  /** 撤销打开的文件。默认只撤 default changelist 里的（changelist 可显式指定）：
   *  编号 changelist 是其它 bug 的成功产物，绝不能误撤（revert 会丢弃其全部改动）。 */
  async revert(files: string[], changelist = "default"): Promise<string> {
    if (!files.length) return "";
    return this.run(["revert", "-c", changelist, ...files]);
  }

  async changeSpec(cl?: number): Promise<string> {
    const args = ["change", "-o"];
    if (cl !== undefined) args.push(String(cl));
    return this.run(args);
  }

  /** 创建新的 pending changelist，返回编号。
   *  传 files 时只把这些文件移入新 changelist（default 中其它文件保持不动）；
   *  不传则按 p4 默认行为把 default 全部 opened 文件移过去 —— 成功路径必须传当前
   *  bug 的文件列表，否则其它 bug 失败遗留的 default 文件会混进本 changelist。 */
  async createPending(description: string, files?: string[]): Promise<number> {
    let spec = await this.changeSpec();
    spec = setSpecField(spec, "Description", description);
    if (files && files.length) {
      spec = setSpecField(spec, "Files", files.join("\n"));
    }
    const out = await this.run(["change", "-i"], spec);
    const m = _CHANGE_CREATED_RE.exec(out);
    if (!m) throw new P4Error(`无法解析创建 changelist 的输出: ${out.trim().slice(0, 300)}`);
    return Number(m[1]);
  }

  async updateDescription(cl: number, description: string): Promise<void> {
    let spec = await this.changeSpec(cl);
    spec = setSpecField(spec, "Description", description);
    await this.run(["change", "-i"], spec);
  }

  /** 仅 auto 模式调用：提交 pending changelist。 */
  async submit(cl: number, description: string): Promise<string> {
    return this.run(["submit", "-d", description, String(cl)], undefined, 600000);
  }
}
